### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by kilianc** [jakiestfu/himawari.js#19]
you really need to close this with your next release :)  #17 

```
$ himawari --zoom 4 -i

Creating himawari-1455408534792.jpg in /Volumes/WS/workspace/foo ...
/Volumes/WS/apps/nvm/versions/node/v5.5.0/lib/node_modules/himawari/index.js:249
    log('Requesting latest date', latest);
    ^

ReferenceError: log is not defined
    at resolveDate (/Volumes/WS/apps/nvm/versions/node/v5.5.0/lib/node_modules/himawari/index.js:249:5)
    at module.exports (/Volumes/WS/apps/nvm/versions/node/v5.5.0/lib/node_modules/himawari/index.js:48:3)
    at Object.<anonymous> (/Volumes/WS/apps/nvm/versions/node/v5.5.0/lib/node_modules/himawari/bin/cli.js:89:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by jakiestfu** [comment]
Fixed in v1.2.6 😬

Sorry about that, mate.
